### ISSUE TITLE
HitsStats and Pagination does not work

### ISSUE THREAD

**Issue by gansaihua** [searchkit/searchkit#732]
**"hits.total is now an object in the search response**

The total hits that match the search request is now returned as an object with a value and a relation. value indicates the number of hits that match and relation indicates whether the value is accurate (eq) or a lower bound (gte)"
e.g.
{
     "_shards": ...
     "timed_out": false,
     "took": 100,
     "hits": {
         "max_score": 1.0,
         "total" : {
             "value": 10000,    
             "relation": "gte"  
         },
         "hits": ...
     }
}

**Comment by joemcelroy** [comment]
hey thanks. Its an issue with elasticsearch 7. Need to build in support for es6 and es7 to handle different response.

**Comment by gansaihua** [comment]
thanks

**Comment by joemcelroy** [comment]
fixed in v2.4.1

**Comment by mcs07** [comment]
I think Pagination with showNumbers is still not working. Looks like #735 only fixes `getHitsCount()`.

Here's are the lines in question.
https://github.com/searchkit/searchkit/blob/9594dbe4613e23f1acbc0765d95451d87e6ae669/packages/searchkit/src/components/search/pagination/src/Pagination.tsx#L72-L76

Possibly `getTotalPages()` could be updated to use `getHitsCount()` instead of duplicating it (with a default of 1 instead of 0)?
